version: '3'
services:
  mysql:
    image: mysql:5.7.23
    container_name: urksib_demo_mysql
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ukrsib_demo

  webapp:
    image: tomcat:8.5-jre8-alpine
    container_name: urksib_demo_webapp
    ports:
      - 8080:8080
    links:
      - mysql:mysql
    depends_on:
      - mysql
    volumes:
      - .:/ukrsib_test_app
    working_dir: /ukrsib_test_app
    command: >
      bash -c "chmod +x deploy_app.sh
      && ./deploy_app.sh"