version: '3'
services:
  mysql:
    image: mysql:5.7.23
    container_name: mysql_demo
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ukrsib_test
    networks:
      - backend

  app:
    image: gradle:4.4.1-jdk8-alpine
    container_name: app_demo
    ports:
      - 8080:8080
    depends_on:
      - mysql
    volumes:
      - .:/ukrsib_test_app
    working_dir: /ukrsib_test_app
    command: >
      sh -c "chmod +x deploy_app_demo.sh
      && ./deploy_app_demo.sh"
    networks:
      - backend

networks:
  backend:
    driver: bridge